load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "commands",
    srcs = ["Commands.cpp"],
    hdrs = ["Commands.hpp"],
    deps = [
        "//Compiler/Cli/Arguments:arguments",
        "//Compiler/Driver:core_pipeline",
        "//Compiler/Linker:native_linker",
        "//Compiler/ProjectSystem/Bridge:project_driver",
        "@fmt//:fmt",
    ],
)
