load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "arguments",
    hdrs = ["Arguments.hpp"],
    strip_include_prefix = "/Interactive/Headers",
)

cc_library(
    name = "history",
    hdrs = ["History.hpp"],
    strip_include_prefix = "/Interactive/Headers",
)

cc_library(
    name = "session",
    hdrs = ["Session.hpp"],
    strip_include_prefix = "/Interactive/Headers",
    deps = [
        "//Compiler/Headers/Visual/XSharp/Backend:llvm_api",
        "//Compiler/Headers/Visual/XSharp:pipeline_api",
        ":history",
    ],
)

cc_library(
    name = "repl_input",
    hdrs = ["ReplInput.hpp"],
    strip_include_prefix = "/Interactive/Headers",
)
