# SPDX-FileCopyrightText: 2026 Leitwolf <support@xsharp-lang.xyz>
# SPDX-License-Identifier: MPL-2.0

org.gradle.daemon=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.jvmargs=-Xms64m -Xmx512m -XX:+UseG1GC -XX:ActiveProcessorCount=1 -XX:MaxMetaspaceSize=256m -XX:CompressedClassSpaceSize=128m -XX:ReservedCodeCacheSize=128m -Xss512k
org.gradle.workers.max=1
