load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "control_flow",
    srcs = ["ControlFlow.cpp"],
    deps = ["//Compiler/Headers/Visual/XSharp/Analysis:control_flow"],
)

cc_library(
    name = "definite_initialization",
    srcs = ["DefiniteInitialization.cpp"],
    deps = ["//Compiler/Headers/Visual/XSharp/Analysis:definite_initialization_api"],
)
