load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "diagnostic_protocol_tests",
    srcs = ["DiagnosticProtocolTests.cpp"],
    deps = [
        "//Compiler/Diagnostic:collection",
        "//Compiler/Diagnostic:protocol",
        "@catch2//:catch2_main",
    ],
)
