load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "control_flow",
    hdrs = ["ControlFlow.hpp"],
    strip_include_prefix = "/Compiler/Headers",
)

cc_library(
    name = "definite_initialization_api",
    hdrs = ["DefiniteInitialization.hpp"],
    strip_include_prefix = "/Compiler/Headers",
)

cc_library(
    name = "ownership_flow_api",
    hdrs = ["OwnershipFlow.hpp"],
    strip_include_prefix = "/Compiler/Headers",
)
