load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "dense_bit_set",
    hdrs = ["DenseBitSet.hpp"],
    strip_include_prefix = "/Compiler/Headers",
    deps = ["@llvm//:llvm"],
)

cc_library(
    name = "control_flow",
    hdrs = ["ControlFlow.hpp"],
    strip_include_prefix = "/Compiler/Headers",
)

cc_library(
    name = "dominance_api",
    hdrs = ["Dominance.hpp"],
    strip_include_prefix = "/Compiler/Headers",
    deps = [":control_flow"],
)

cc_library(
    name = "control_dependence_api",
    hdrs = ["ControlDependence.hpp"],
    strip_include_prefix = "/Compiler/Headers",
    deps = [":dominance_api"],
)

cc_library(
    name = "definite_initialization_api",
    hdrs = ["DefiniteInitialization.hpp"],
    strip_include_prefix = "/Compiler/Headers",
    deps = [":worklist_api"],
)

cc_library(
    name = "ownership_flow_api",
    hdrs = ["OwnershipFlow.hpp"],
    strip_include_prefix = "/Compiler/Headers",
    deps = [":worklist_api"],
)

cc_library(
    name = "liveness_api",
    hdrs = ["Liveness.hpp"],
    strip_include_prefix = "/Compiler/Headers",
    deps = [":worklist_api"],
)

cc_library(
    name = "worklist_api",
    hdrs = ["Worklist.hpp"],
    strip_include_prefix = "/Compiler/Headers",
    deps = [":control_flow"],
)
