load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "llvm_backend",
    srcs = ["Artifact.cpp", "Codegen.cpp", "Verifier.cpp"],
    deps = [
        "//Compiler/Codegen/Xmm:xmm",
        "//Compiler/Headers/Visual/XSharp/Backend:llvm_api",
        "//Compiler/Headers/Visual/XSharp/Core:scalar",
        "@llvm//:llvm",
    ],
)
