load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "xmm_verifier_tests",
    srcs = [
        "OptimizerTests.cpp",
        "OwnershipVerifierTests.cpp",
        "VerifierTests.cpp",
    ],
    deps = [
        "//Compiler/Codegen/Xmm:xmm",
        "//Compiler/Headers/Visual/XSharp/Core:scalar",
        "@catch2//:catch2_main",
    ],
)
