load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "wire_support",
    srcs = ["WireSupport.cpp"],
    deps = [
        "//Compiler/Core:core",
        "//Compiler/Headers/Visual/XSharp/Artifact:wire_support_api",
        "//Compiler/Headers/Visual/XSharp/Core:scalar",
    ],
)
