load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "protocol_api",
    hdrs = ["Protocol.hpp"],
    include_prefix = "Visual/XSharp/Diagnostic",
    strip_include_prefix = ".",
    deps = ["//Compiler/Headers/Visual/XSharp/Artifact:wire_support_api"],
)

cc_library(
    name = "collection_api",
    hdrs = ["Collection.hpp"],
    include_prefix = "Visual/XSharp/Diagnostic",
    strip_include_prefix = ".",
    deps = [":protocol_api"],
)
