cabal-version: 3.12
-- SPDX-FileCopyrightText: 2026 Progmasoft <support@progmasoft.com>
-- SPDX-License-Identifier: MPL-2.0 WITH AdditionRef-Progmasoft-Exception-1.0
name: visual-xsharp-frontend
version: 0.3.3
synopsis: Visual X# resolution and type-checking frontend
license: MPL-2.0
author: Progmasoft
maintainer: support@progmasoft.com
build-type: Simple

library
    exposed-modules:
        Visual.XSharp.Closure.Analysis
        Visual.XSharp.Frontend
        Visual.XSharp.Resolver.NameResolution
        Visual.XSharp.Resolver.Renamer
        Visual.XSharp.SourceSet
        Visual.XSharp.TypeChecker
    hs-source-dirs: src
    build-depends:
        base >=4.20 && <4.23,
        bytestring >=0.12 && <0.14,
        containers >=0.7 && <0.9,
        directory >=1.3 && <1.4,
        filepath >=1.5 && <1.6,
        text >=2.1 && <2.3,
        visual-xsharp-syntax
    default-language: GHC2021
