// SPDX-FileCopyrightText: 2026 Progmasoft <support@progmasoft.com>
// SPDX-License-Identifier: MPL-2.0 WITH AdditionRef-Progmasoft-Exception-1.1

package executioncases

import (
	"fmt"
	"strings"
)

const license = `SPDX-FileCopyrightText: 2026 Progmasoft <support@progmasoft.com>
SPDX-License-Identifier: MPL-2.0 WITH AdditionRef-Progmasoft-Exception-1.1`

// A Table is one case file and the names its cases have in the generated
// sources.
type Table struct {
	// Source is the case file, relative to the repository root.
	Source string
	// Include is the generated C++ table, relative to the repository root.
	Include string
	// Binding is the name of the list in the generated Haskell module.
	Binding string
	// Summary is the Haddock comment of that list.
	Summary string
	Cases   []Case
}

// quote writes a string literal that Haskell and C++ read the same way: a
// case body is one line of printable source, so only the backslash and the
// quotation mark need an escape.
func quote(text string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(text) + `"`
}

// RenderInclude writes the rows of a C++ array of `ExecutionCase`, one row
// for each run, in file order.
func RenderInclude(table Table) string {
	var out strings.Builder
	for _, line := range strings.Split(license, "\n") {
		out.WriteString("// " + line + "\n")
	}
	out.WriteString("//\n")
	out.WriteString("// Generated from " + table.Source + " by\n")
	out.WriteString("// `go -C helpers run ./cmd/execution-cases generate`. Do not edit.\n")
	out.WriteString("//\n")
	out.WriteString("// clang-format off\n")
	for _, current := range table.Cases {
		for _, comment := range current.Comment {
			out.WriteString(strings.TrimRight("// "+comment, " ") + "\n")
		}
		for _, run := range current.Runs {
			fmt.Fprintf(&out, "{ %t, %t, %d, %d, %d,\n  %s },\n",
				run.Flag, run.Other, run.Left, run.Right, run.Expected, quote(current.Body))
		}
	}
	out.WriteString("// clang-format on\n")
	return out.String()
}

// RenderHaskell writes the module that holds every table as a list.
func RenderHaskell(tables []Table) string {
	var out strings.Builder
	for _, line := range strings.Split(license, "\n") {
		out.WriteString("-- " + line + "\n")
	}
	out.WriteString(`
{- | The programs that "BranchingTests" runs, with the value each must return.

Generated by @go -C helpers run ./cmd/execution-cases generate@. Do not edit:
the cases are written in the files under @Compiler/Fuzzing/Cases@, which also
generate the tables the native smoke program @source_execution_smoke@ runs
through LLVM.

A case is the body of @int Run(bool flag, bool other, int left, int right)@
and the runs of that body. The expected values are written by hand from the
language rules.
-}
module BranchingEvaluationCases
    ( EvaluationCase
    , evaluationCases
`)
	for _, table := range tables {
		out.WriteString("    , " + table.Binding + "\n")
	}
	out.WriteString(`    ) where

-- | A body, and for each run its arguments and the value it must return.
type EvaluationCase = (String, [((Bool, Bool, Integer, Integer), Integer)])

-- | Every case, in the order the tests report them.
evaluationCases :: [EvaluationCase]
evaluationCases = `)
	names := make([]string, 0, len(tables))
	for _, table := range tables {
		names = append(names, table.Binding)
	}
	out.WriteString(strings.Join(names, " ++ ") + "\n")
	for _, table := range tables {
		out.WriteString("\n-- | " + table.Summary + " From @" + table.Source + "@.\n")
		out.WriteString(table.Binding + " :: [EvaluationCase]\n")
		out.WriteString(table.Binding + " =\n")
		for index, current := range table.Cases {
			opener := "    , "
			if index == 0 {
				opener = "    [ "
			}
			if len(current.Comment) == 0 {
				out.WriteString(strings.TrimRight(opener, " ") + "\n")
			}
			for line, comment := range current.Comment {
				prefix := "      "
				if line == 0 {
					prefix = opener
				}
				out.WriteString(strings.TrimRight(prefix+"-- "+comment, " ") + "\n")
			}
			out.WriteString("        ( " + quote(current.Body) + "\n")
			runs := make([]string, 0, len(current.Runs))
			for _, run := range current.Runs {
				runs = append(runs, fmt.Sprintf("((%s, %s, %d, %d), %d)",
					haskellBool(run.Flag), haskellBool(run.Other), run.Left, run.Right, run.Expected))
			}
			out.WriteString("        , [" + strings.Join(runs, ", ") + "]\n")
			out.WriteString("        )\n")
		}
		out.WriteString("    ]\n")
	}
	return out.String()
}

func haskellBool(value bool) string {
	if value {
		return "True"
	}
	return "False"
}
