// SPDX-FileCopyrightText: 2026 Progmasoft <support@progmasoft.com>
// SPDX-License-Identifier: MPL-2.0 WITH AdditionRef-Progmasoft-Exception-1.1

#include <array>
#include <cstdint>
#include <llvm/Support/raw_ostream.h>
#include <string>
#include <string_view>

#include "ExpressionExecutionCases.hpp"
#include "SourceFuzz.hpp"

// Executable regressions for expressions that store into locals:
// assignments and increments used as values, and loops used as expressions.
// Each case is a method body, the arguments it runs on and the value it must
// return. The expected values are written by hand from the language rules:
// operands are evaluated left to right, an assignment yields the stored
// value, a prefix form the new value, a postfix form the previous one, and a
// loop expression the operand of the break that leaves it. The same table
// is checked against a reference evaluator in the frontend test suite; here
// every case runs through CorePrep, Xpp, Xmm, LLVM and the ORC JIT,
// unoptimized and optimized.

namespace Visual::XSharp::Fuzzing
{
    namespace
    {
        struct Case final
        {
            bool flag;
            bool other;
            int left;
            int right;
            std::int64_t expected;
            std::string_view body;
        };

        constexpr std::array<Case, 122U> kCases{ {
            { false,
              false,
              3,
              4,
              44,
              "int a = left; int b = (a = right); return a * 10 + b;" },
            { false,
              false,
              0,
              9,
              99,
              "int a = left; int b = (a = right); return a * 10 + b;" },
            { false,
              false,
              3,
              0,
              33,
              "int a = 0; int b = 0; a = b = left; return a * 10 + b;" },
            { false,
              false,
              5,
              0,
              15,
              "int a = 1; int b = 2; int c = 3; a = b = c = left; return a + b "
              "+ c;" },
            { false, false, 3, 4, 4, "int a = left; return a = right;" },
            { false, false, 3, 4, 7, "int a = left; return a + (a = right);" },
            { false,
              false,
              10,
              1,
              11,
              "int a = left; return a + (a = right);" },
            { false, false, 3, 4, 8, "int a = left; return (a = right) + a;" },
            { false,
              false,
              3,
              4,
              16,
              "int a = left; return (a + 1) * (a = right);" },
            { false,
              false,
              3,
              4,
              11,
              "int a = left; return a + (a = right) + a;" },
            { false,
              false,
              10,
              3,
              4,
              "int a = left; return a - (a = right) - a;" },
            { false,
              false,
              0,
              0,
              9,
              "int a = left; return (a = 2) * (a = 3) + a;" },
            { false, false, 3, 4, 0, "int a = left; return -(a = right) + a;" },
            { false,
              false,
              3,
              4,
              10,
              "int a = left; int b = right; return (a = b) + (b = 1) + a + "
              "b;" },
            { false, false, 3, 0, 7, "int a = left; return a++ + a;" },
            { false, false, 3, 0, 8, "int a = left; return ++a + a;" },
            { false, false, 3, 0, 7, "int a = left; return a++ + a++;" },
            { false, false, 3, 0, 20, "int a = left; return ++a * ++a;" },
            { false,
              false,
              3,
              0,
              43,
              "int a = left; int b = a++; return a * 10 + b;" },
            { false,
              false,
              3,
              0,
              44,
              "int a = left; int b = ++a; return a * 10 + b;" },
            { false, false, 3, 0, 10, "int a = left; return a + a++ + a;" },
            { false,
              false,
              3,
              4,
              14,
              "int a = left; int total = (a += right); return a + total;" },
            { false,
              false,
              3,
              4,
              7,
              "int a = left; a += (a = right); return a;" },
            { false,
              false,
              10,
              4,
              6,
              "int a = left; a -= (a = right); return a;" },
            { false,
              false,
              3,
              0,
              24,
              "int a = left; return (a += 1) * (a += 2);" },
            { false,
              false,
              3,
              4,
              17,
              "int a = left; return a + (a += right) + a;" },
            { false, false, 3, 0, 9, "int a = left; a *= a++; return a;" },
            { false,
              false,
              0,
              4,
              66,
              "int a = left; int b = right; a = b += 2; return a * 10 + b;" },
            { false,
              false,
              3,
              4,
              63,
              "int a = left; int b = right; a += b -= 1; return a * 10 + b;" },
            { false, false, 3, 0, 24, "int a = left; return (a <<= 2) + a;" },
            { false,
              false,
              17,
              5,
              4,
              "int a = left; return (a %= right) + a;" },
            { false,
              false,
              6,
              3,
              3,
              "int a = left; return (a &= right) | (a ^= 1);" },
            { false,
              false,
              3,
              4,
              12,
              "int a = left; return Twice(a = right) + a;" },
            { false,
              false,
              3,
              4,
              10,
              "int a = left; return Twice(a) + (a = right);" },
            { false,
              false,
              10,
              3,
              7,
              "int a = left; return Minus(a, a = right);" },
            { false,
              false,
              10,
              3,
              0,
              "int a = left; return Minus(a = right, a);" },
            { false, false, 5, 0, -1, "int a = left; return Minus(a++, a++);" },
            { false,
              false,
              1,
              2,
              122,
              "int a = left; return Pick(a, a = right, a);" },
            { false,
              false,
              1,
              0,
              123,
              "int a = left; return Pick(a++, a++, a);" },
            { false,
              false,
              1,
              0,
              224,
              "int a = left; return Pick(Twice(a), a += 1, Twice(a));" },
            { true,
              false,
              7,
              0,
              11,
              "int a = left; int r = flag ? (a = 1) : (a = 2); return a * 10 + "
              "r;" },
            { false,
              false,
              7,
              0,
              22,
              "int a = left; int r = flag ? (a = 1) : (a = 2); return a * 10 + "
              "r;" },
            { true,
              false,
              3,
              4,
              200,
              "int a = left; int r = flag ? (a = 100) : right; return a + r;" },
            { false,
              false,
              3,
              4,
              7,
              "int a = left; int r = flag ? (a = 100) : right; return a + r;" },
            { true,
              false,
              3,
              4,
              7,
              "int a = left; int r = flag ? right : (a = 100); return a + r;" },
            { false,
              false,
              3,
              4,
              200,
              "int a = left; int r = flag ? right : (a = 100); return a + r;" },
            { false,
              false,
              3,
              4,
              5,
              "int a = left; int r = (a = right) ? a + 1 : -1; return r;" },
            { false,
              false,
              3,
              0,
              -1,
              "int a = left; int r = (a = right) ? a + 1 : -1; return r;" },
            { true,
              true,
              9,
              0,
              11,
              "int a = left; int r = flag ? (other ? (a = 1) : (a = 2)) : (a = "
              "3); return a * 10 + r;" },
            { true,
              false,
              9,
              0,
              22,
              "int a = left; int r = flag ? (other ? (a = 1) : (a = 2)) : (a = "
              "3); return a * 10 + r;" },
            { false,
              true,
              9,
              0,
              33,
              "int a = left; int r = flag ? (other ? (a = 1) : (a = 2)) : (a = "
              "3); return a * 10 + r;" },
            { true,
              false,
              3,
              4,
              11,
              "int a = left; return a + (flag ? (a = right) : 0) + a;" },
            { false,
              false,
              3,
              4,
              6,
              "int a = left; return a + (flag ? (a = right) : 0) + a;" },
            { true,
              false,
              0,
              0,
              105,
              "int a = 0; bool r = flag && (a = 5) > 0; return a + (r ? 100 : "
              "0);" },
            { false,
              false,
              0,
              0,
              0,
              "int a = 0; bool r = flag && (a = 5) > 0; return a + (r ? 100 : "
              "0);" },
            { true,
              false,
              0,
              0,
              0,
              "int a = 9; bool r = flag && (a = 0) > 0; return a + (r ? 100 : "
              "0);" },
            { false,
              false,
              0,
              0,
              9,
              "int a = 9; bool r = flag && (a = 0) > 0; return a + (r ? 100 : "
              "0);" },
            { true,
              false,
              0,
              0,
              100,
              "int a = 0; bool r = flag || (a = 5) > 3; return a + (r ? 100 : "
              "0);" },
            { false,
              false,
              0,
              0,
              105,
              "int a = 0; bool r = flag || (a = 5) > 3; return a + (r ? 100 : "
              "0);" },
            { false,
              false,
              0,
              0,
              5,
              "int a = 0; bool r = flag || (a = 5) > 7; return a + (r ? 100 : "
              "0);" },
            { false,
              false,
              3,
              4,
              104,
              "int a = 0; bool r = (a = left) > 0 && (a = right) > 0; return a "
              "+ (r ? 100 : 0);" },
            { false,
              false,
              0,
              4,
              0,
              "int a = 0; bool r = (a = left) > 0 && (a = right) > 0; return a "
              "+ (r ? 100 : 0);" },
            { false,
              false,
              3,
              0,
              0,
              "int a = 0; bool r = (a = left) > 0 && (a = right) > 0; return a "
              "+ (r ? 100 : 0);" },
            { true,
              false,
              0,
              0,
              112,
              "int a = 0; int b = 0; bool r = flag && (a = 1) > 0 && (b = 2) > "
              "0; return a * 10 + b + (r ? 100 : 0);" },
            { false,
              false,
              0,
              0,
              0,
              "int a = 0; int b = 0; bool r = flag && (a = 1) > 0 && (b = 2) > "
              "0; return a * 10 + b + (r ? 100 : 0);" },
            { true,
              true,
              0,
              0,
              100,
              "int a = 0; bool r = flag && other || (a = 5) > 0; return a + (r "
              "? 100 : 0);" },
            { true,
              false,
              0,
              0,
              105,
              "int a = 0; bool r = flag && other || (a = 5) > 0; return a + (r "
              "? 100 : 0);" },
            { false,
              false,
              4,
              0,
              4,
              "int a = 0; int r = left ?: (a = 9); return a * 100 + r;" },
            { false,
              false,
              0,
              0,
              909,
              "int a = 0; int r = left ?: (a = 9); return a * 100 + r;" },
            { false,
              false,
              3,
              4,
              44,
              "int a = left; int r = (a = right) ?: 7; return a * 10 + r;" },
            { false,
              false,
              3,
              0,
              7,
              "int a = left; int r = (a = right) ?: 7; return a * 10 + r;" },
            { false,
              false,
              5,
              0,
              5,
              "int a = 0; if ((a = left) > 2) { return a; } return -a;" },
            { false,
              false,
              1,
              0,
              -1,
              "int a = 0; if ((a = left) > 2) { return a; } return -a;" },
            { false,
              false,
              4,
              0,
              65,
              "int n = 0; int sum = 0; int v = 0; while ((v = n++) < left) { "
              "sum += v; } return sum * 10 + n;" },
            { false,
              false,
              0,
              0,
              1,
              "int n = 0; int sum = 0; int v = 0; while ((v = n++) < left) { "
              "sum += v; } return sum * 10 + n;" },
            { false,
              false,
              4,
              0,
              4,
              "int n = 0; int sum = 0; int v = 0; while ((v = n++) < left) { "
              "if (v == 2) { continue; } sum += v; } return sum;" },
            { false,
              false,
              4,
              0,
              13,
              "int n = 0; int sum = 0; int v = 0; while ((v = n++) < left) { "
              "if (v == 2) { break; } sum += v; } return sum * 10 + n;" },
            { false,
              false,
              3,
              0,
              34,
              "int n = 0; int count = 0; while (n++ < left) { count++; } "
              "return count * 10 + n;" },
            { false,
              false,
              3,
              0,
              23,
              "int n = 0; int count = 0; while (++n < left) { count++; } "
              "return count * 10 + n;" },
            { false,
              false,
              3,
              0,
              3,
              "int n = left; int count = 0; do { count++; } while ((n = n - 1) "
              "> 0); return count;" },
            { false,
              false,
              0,
              0,
              1,
              "int n = left; int count = 0; do { count++; } while ((n = n - 1) "
              "> 0); return count;" },
            { false,
              false,
              3,
              0,
              23,
              "int n = left; int count = 0; do { count++; if (count == 12) { "
              "continue; } count += 10; } while ((n -= 1) > 0); return "
              "count;" },
            { false,
              false,
              5,
              0,
              24,
              "int n = left; int count = 0; do { count++; if (count == 2) { "
              "break; } } while ((n -= 1) > 0); return count * 10 + n;" },
            { false,
              false,
              3,
              0,
              44,
              "int n = 0; int count = 0; do { count++; } while (n++ < left); "
              "return count * 10 + n;" },
            { false,
              false,
              7,
              0,
              10,
              "int sum = 0; int v = 0; for (int i = 0; (v = i * 2) < left; "
              "i++) { if (v == 2) { continue; } sum += v; } return sum;" },
            { false,
              false,
              7,
              0,
              24,
              "int sum = 0; int v = 0; for (int i = 0; (v = i * 2) < left; "
              "i++) { if (v == 4) { break; } sum += v; } return sum * 10 + "
              "v;" },
            { false,
              false,
              3,
              0,
              6,
              "int sum = 0; for (int i = 0; i++ < left; i += 0) { sum += i; } "
              "return sum;" },
            { false,
              false,
              3,
              0,
              9,
              "int total = 0; for (int i = 0; i < left; i += 1) { int j = 0; "
              "while ((j += 1) < 3) { total += i * j; } } return total;" },
            { false, false, 3, 4, 4, "int a = left; (a = right); return a;" },
            { false,
              false,
              3,
              4,
              4,
              "int a = left; _ = (a = right); return a;" },
            { false,
              false,
              3,
              4,
              4,
              "int a = left; _ = Twice(a = right); return a;" },
            { false,
              false,
              3,
              0,
              5,
              "int a = left; _ = a++; _ = ++a; return a;" },
            { false,
              false,
              1,
              0,
              64,
              "int a = left; int b = 0; b = a++ + a++ + a++; return b * 10 + "
              "a;" },
            { false,
              false,
              3,
              4,
              7,
              "int a = left; bool big = (a += right) is > 5; return big ? a : "
              "-a;" },
            { false,
              false,
              1,
              2,
              -3,
              "int a = left; bool big = (a += right) is > 5; return big ? a : "
              "-a;" },
            { false,
              false,
              7,
              0,
              7,
              "int r = while (true) { break left; }; return r;" },
            { false,
              false,
              10,
              0,
              4,
              "int n = 0; int r = while (true) { n += 1; if (n * n > left) { "
              "break n; } }; return r;" },
            { false,
              false,
              0,
              0,
              1,
              "int n = 0; int r = while (true) { n += 1; if (n * n > left) { "
              "break n; } }; return r;" },
            { false,
              false,
              10,
              0,
              4,
              "int r = for (int i = 0; ; i++) { if (i * 3 >= left) { break i; "
              "} }; return r;" },
            { false,
              false,
              0,
              0,
              0,
              "int r = for (int i = 0; ; i++) { if (i * 3 >= left) { break i; "
              "} }; return r;" },
            { false,
              false,
              5,
              0,
              60,
              "int r = for (int i = 0; true; i += 2) { if (i > left) { break i "
              "* 10; } }; return r;" },
            { false,
              false,
              5,
              0,
              1131,
              "int n = left; int r = while (true) { if (n > 100) { break 1; } "
              "if (n < 0) { break 0 - 1; } n = n * 2 - 3; }; return r * 1000 + "
              "n;" },
            { false,
              false,
              2,
              0,
              -1001,
              "int n = left; int r = while (true) { if (n > 100) { break 1; } "
              "if (n < 0) { break 0 - 1; } n = n * 2 - 3; }; return r * 1000 + "
              "n;" },
            { false,
              false,
              0,
              3,
              7,
              "int r = while (true) { int inner = for (int j = 0; ; j++) { if "
              "(j == right) { break j * 2; } }; break inner + 1; }; return "
              "r;" },
            { false,
              false,
              3,
              0,
              15,
              "int a = left; return a + while (true) { a += 1; if (a > 5) { "
              "break a; } } + a;" },
            { false,
              false,
              9,
              0,
              29,
              "int a = left; return a + while (true) { a += 1; if (a > 5) { "
              "break a; } } + a;" },
            { false,
              false,
              4,
              0,
              8,
              "int n = 0; int sum = 0; int r = while (true) { n++; if (n == 2) "
              "{ continue; } sum += n; if (n >= left) { break sum; } }; return "
              "r;" },
            { false,
              false,
              7,
              0,
              9,
              "int total = 0; int r = while (true) { int k = 0; while (true) { "
              "k++; if (k == 3) { break; } } total += k; if (total > left) { "
              "break total; } }; return r;" },
            { true,
              false,
              0,
              0,
              1,
              "bool found = while (true) { break flag; }; return found ? 1 : "
              "0;" },
            { false,
              false,
              0,
              0,
              0,
              "bool found = while (true) { break flag; }; return found ? 1 : "
              "0;" },
            { true,
              false,
              3,
              4,
              33,
              "int a = 0; int r = while (true) { if (flag) { break a = left; } "
              "break (a += right); }; return r * 10 + a;" },
            { false,
              false,
              3,
              4,
              44,
              "int a = 0; int r = while (true) { if (flag) { break a = left; } "
              "break (a += right); }; return r * 10 + a;" },
            { true,
              false,
              0,
              0,
              33,
              "int a = 0; int r = flag ? while (true) { a += 1; if (a == 3) { "
              "break a; } } : 7; return r * 10 + a;" },
            { false,
              false,
              0,
              0,
              70,
              "int a = 0; int r = flag ? while (true) { a += 1; if (a == 3) { "
              "break a; } } : 7; return r * 10 + a;" },
            { false,
              false,
              4,
              0,
              6,
              "int n = 0; int sum = 0; while (for (int i = n; ; i++) { if (i "
              ">= n) { break i; } } < left) { sum += n; n++; } return sum;" },
            { false,
              false,
              7,
              0,
              27,
              "int n = 0; int r = Twice(while (true) { n += 3; if (n > left) { "
              "break n; } }) + n; return r;" },
            { true,
              false,
              5,
              0,
              61,
              "int n = left; bool big = flag && while (true) { n += 1; break n "
              "> 5; }; return n * 10 + (big ? 1 : 0);" },
            { true,
              false,
              1,
              0,
              20,
              "int n = left; bool big = flag && while (true) { n += 1; break n "
              "> 5; }; return n * 10 + (big ? 1 : 0);" },
            { false,
              false,
              5,
              0,
              50,
              "int n = left; bool big = flag && while (true) { n += 1; break n "
              "> 5; }; return n * 10 + (big ? 1 : 0);" },
            { false,
              false,
              4,
              0,
              404,
              "int n = 0; int r = (n = left) ?: while (true) { n += 7; break "
              "n; }; return r * 100 + n;" },
            { false,
              false,
              0,
              0,
              707,
              "int n = 0; int r = (n = left) ?: while (true) { n += 7; break "
              "n; }; return r * 100 + n;" },
            { false,
              false,
              0,
              0,
              1,
              "long wide = while (true) { break 10; }; return wide > 9 ? 1 : "
              "0;" },
        } };

        [[nodiscard]] auto
        Truth(bool value) -> std::string
        {
            // `Id` is recursive, so the optimizer cannot fold the arguments
            // away and the body really executes on run-time values.
            return value ? "Id(1) > 0" : "Id(0) > 0";
        }

        [[nodiscard]] auto
        Program(const Case &entry) -> std::string
        {
            return "namespace Fuzz;\n"
                   "class Program {\n"
                   "    public static int Id(_ int n) { return n > 0 ? 1 + "
                   "Id(n - 1) : 0; }\n"
                   "    public static int Next() { return 7; }\n"
                   "    public static int Twice(_ int value) { return value + "
                   "value; }\n"
                   "    public static int Minus(_ int first, _ int second) { "
                   "return first - second; }\n"
                   "    public static int Pick(_ int first, _ int second, _ "
                   "int "
                   "third) { return first * 100 + second * 10 + third; }\n"
                   "    public static void Touch() { }\n"
                   "    public static int Run(_ bool flag, _ bool other, _ int "
                   "left, _ int right) {\n        "
                   + std::string(entry.body)
                   + "\n    }\n"
                     "    public static int Evaluate() { return Run("
                   + Truth(entry.flag) + ", " + Truth(entry.other) + ", Id("
                   + std::to_string(entry.left) + "), Id("
                   + std::to_string(entry.right) + ")); }\n}\n";
        }
    } // namespace

    void
    ExerciseExpressionCases()
    {
        for (const auto &entry : kCases)
        {
            llvm::errs() << "Expression execution: " << entry.body << '\n';
            ExerciseExpectedValue(Program(entry), entry.expected);
        }
    }
} // namespace Visual::XSharp::Fuzzing
