load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "xmm_benches",
    srcs = ["XmmBenches.cpp"],
    deps = [
        "//Compiler/Codegen/Xmm:xmm",
        "//Compiler/Codegen/Xpp:xpp",
        "//Compiler/Headers/Visual/XSharp/Core:scalar",
        "//Compiler/Headers/Visual/XSharp/Xmm:xmm",
        "//Compiler/Headers/Visual/XSharp/Xpp:xpp",
        "@google_benchmark//:benchmark_main",
    ],
)
