load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "xpp",
    hdrs = ["IR.hpp", "Verifier.hpp", "Wire.hpp"],
    strip_include_prefix = "/Compiler/Headers",
    deps = [
        "//Compiler/Headers/Visual/XSharp/Artifact:wire_support_api",
        "//Compiler/Headers/Visual/XSharp/Core:coreprep_model",
    ],
)
