load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "text_runtime_tests",
    srcs = ["TextRuntimeTests.cpp"],
    deps = [
        "//Compiler/Headers/Visual/XSharp/Runtime:aarc_api",
        "//Compiler/Headers/Visual/XSharp/Runtime:text_api",
        "//Compiler/Runtime/AARC:aarc",
        "//Compiler/Runtime/Text:text",
        "@catch3//:catch2_main",
        "@catch3//src/Progmasoft:catch3",
    ],
)
