# SPDX-FileCopyrightText: 2026 Leitwolf <support@xsharp-lang.xyz>
# SPDX-License-Identifier: Apache-2.0

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name java.xsharp-lang.xyz;

    root /srv/xsharp/java;
    index index.html;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/xsharp-lang.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xsharp-lang.xyz/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Content-Security-Policy "default-src 'self'; base-uri 'none'; frame-ancestors 'none'; object-src 'none'" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;

    location = /org/xsslang/xlil/maven-metadata.xml {
        add_header Cache-Control "no-cache" always;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }
}
